name: dart_discord_bot
description: Discord bot using public API
version: 1.0.0


environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
    nyxx: ^5.0.0
    sqlite3: ^1.3.0
    sqlite3_flutter_libs: ^0.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
